name: e-motion
type: environment
description: Environment for e-motion D4G
dependencies:
- python=3.9
- geopandas=0.12.2
- folium=0.14.0
- sklearn=1.2.2
- conda-forge::umap_learn=0.5.3
- pyarrow=10.0.1
- seaborn=0.12.2
- conda-forge::ipywidgets=8.0.4
- conda-forge::dask-geopandas=0.3.0
- conda-forge::css-html-js-minify
